"""empty message

Revision ID: 0fb394f6a2a8
Revises: 5218fee94fa4
Create Date: 2023-09-11 09:56:21.138260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb394f6a2a8'
down_revision = '5218fee94fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dilemma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('choice_a', sa.String(length=25), nullable=False))
        batch_op.add_column(sa.Column('choice_b', sa.String(length=25), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dilemma', schema=None) as batch_op:
        batch_op.drop_column('choice_b')
        batch_op.drop_column('choice_a')

    # ### end Alembic commands ###
